### PR TITLE
Use dep to manage dependencies

### PR DESCRIPTION
**Pull request by c633**
How to use `dep` (https://github.com/golang/dep)

1. Install `dep`: `brew install dep`
2. Download dependencies to `vendor` directory: `dep ensure`
3. Done

### CODE REVIEW

**Comment by c633** [comment]
I don't think `dep` is supported in Travis as it's still an open issue (https://github.com/travis-ci/travis-ci/issues/8301).

**Comment by c633** [comment]
I added a TODO to our Travis script so we don't forget this.

**Comment by masomel** [comment]
Great, thanks!

**Comment by corbym** [comment]
You can use dep with travis right now:

```yaml
sudo: false
language: go
go:
  - 1.9.x
  - master
before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - go test
matrix:
  allow_failures:
    - go: master
  fast_finish: true
notifications:
  email: false
.. etc..
```

**Pull request merged**
