### PR TITLE
Add proof for STRs and TBs

### LINKED ISSUE #24: Add verification function to STRs and TBs
See https://github.com/coniks-sys/libmerkleprefixtree-go/pull/21#discussion_r71615961
Thus, it would make sense to expose a ``verify()`` or ``prove()`` function for STRs and temporary bindings.

### PR DESCRIPTION
**Pull request by c633**
* Resolve #24

* The `TB` also publishes the `IndexProof` after `vrf_integration` branch is merged.

### CODE REVIEW

**Comment by arlolra** [comment]
Merged in 812caad4b217283dbed1735de8f22a102602ddea

**Comment by masomel** [comment]
I was still reviewing this PR. I didn't think it was ready.

**Comment by arlolra** [comment]
Oh no!  Sorry, let me back that out then.  One sec.

**Comment by masomel** [comment]
Thanks! Sorry for the hassle!

**Comment by arlolra** [comment]
No hassle, let's get it right.

**Comment by arlolra** [comment]
Please see #35 ...

**Pull request closed without merging**
